# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11aa10e359cec6c3b22b3f2da09ebea02f9fa96ad28ee6260b687e4539fd8a84189568b3acd7632e046258ffead1b48629364ed25d93aa8837010e434bcb6c57

test:
  secret_key_base: 54e026b1580c56fa659d808908810eea69f971ea10ba91e6ff140a31ad5506f8f5872304377c398ed2e20a47ffef1de2ceebfbdf3e82207634b3bb4b39760571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
